/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "stm32f401xx.h"

GPIO_Config_t led_blink = {
		.GPIO_MODE = GPIO_MODE_OUTPUT,
		.GPIO_PIN = GPIO_PIN_1,
		.GPIO_OUT_TYPE = GPIO_OUTPUT_PUSH_PULL,
		.GPIO_PUPD = GPIO_PULL_UP
};

GPIO_Config_t led_blink1 = {
		.GPIO_MODE = GPIO_MODE_OUTPUT,
		.GPIO_PIN = GPIO_PIN_0,
		.GPIO_OUT_TYPE = GPIO_OUTPUT_PUSH_PULL,
		.GPIO_PUPD = GPIO_PULL_UP
};

GPIO_Config_t button_state = {
		.GPIO_MODE = GPIO_MODE_INPUT,
		.GPIO_PIN = GPIO_PIN_0,
		.GPIO_PUPD = GPIO_PULL_UP,
		.GPIO_IT_TRIGGER_MODE = GPIO_IT_FALLING_RAISING
};


TIMER_Config_t timer_config  = {
		.AutoReload = 1000,
		.ClockDivision = CLOCK_DIVINE_BY_1,
		.CounterMode = COUNTER_MODE_UP,
		.Prescaler = 15999,
		.is_enable_OnePulse = false,
		.UpdateSource = TIMER_UPDATE_ALL_EVENT,
		.is_enable_Preload = false,
		.CounterValue = 0
};


uint32_t test = 0;
uint32_t result = 0;

volatile uint32_t timer_count = 0;
volatile uint32_t button_count = 0;

/* Timer interrupt */
void TIM2_IRQHandler(void)
{
    if(TIMER2->SR & (1U << 0))
    {
        TIMER2->SR &= ~(1U << 0);
        GPIO_PinOutToggle(GPIOA, GPIO_PIN_1);
    }
}

/* Button interrupt */
void EXTI0_IRQHandler(void)
{
    if(EXTI->PR & (1U << 0))
    {
        EXTI->PR = (1U << 0);
        GPIO_PinOutToggle(GPIOA, GPIO_PIN_0);  // LED khác
    }
}

int main(void)
{
	RCC_InitSystemClock(RCC_CLOCK_84MHZ);
    GPIO_Init_Mode(GPIOA, &led_blink);
    GPIO_Init_Mode(GPIOA, &led_blink1);
    TIMER_BASE_Init_IT(TIMER2, &timer_config, 3);
    GPIO_Init_IT(GPIOB, &button_state, 1);

    //result = TIMER2->ARR;
    TIMER_Start(TIMER2);
	for(;;)
	{
		test = TIMER2->CNT;
		//if (test == result) // UIF
		//{
			//TIMER2->SR &= ~(1U << 0);
		//	GPIO_PinOutToggle(GPIOA, GPIO_PIN_1);
		//}
	}
}
